import React from 'react';
// import { Inter } from 'next/font/google';
import './globals.css';
import propTypes from 'prop-types';

// const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className=''>{children}</body>
        </html>
    );
}

RootLayout.propTypes = {
    children: propTypes.node,
};
